-- Inserindo 5 agencias
INSERT INTO AGENCIA (ID, NOME, NUMERO_AGENCIA) VALUES (1,'Agencia Sul', 101);
INSERT INTO AGENCIA (ID, NOME, NUMERO_AGENCIA) VALUES (2,'Agencia Sudeste', 202);
INSERT INTO AGENCIA (ID, NOME, NUMERO_AGENCIA) VALUES (3,'Agencia Centro-Oeste', 303);
INSERT INTO AGENCIA (ID, NOME, NUMERO_AGENCIA) VALUES (5,'Agencia Nordeste', 404);
INSERT INTO AGENCIA (ID, NOME, NUMERO_AGENCIA) VALUES (4,'Agencia Norte', 505);

-- Inserindo 6 clientes
INSERT INTO CLIENTE (NOME, EMAIL, TELEFONE) VALUES ('Allan Lopreti', 'lopreti@email.com', '(11)99999-9999');
INSERT INTO CLIENTE (NOME, EMAIL, TELEFONE) VALUES ('Allan Felintro', 'felintro@email.com', '(11)99999-9999');
INSERT INTO CLIENTE (NOME, EMAIL, TELEFONE) VALUES ('Caio Paiva', 'paiva@email.com', '(11)99999-9999');
INSERT INTO CLIENTE (NOME, EMAIL, TELEFONE) VALUES ('Marcos Nofre', 'nofre@email.com', '(11)99999-9999');
INSERT INTO CLIENTE (NOME, EMAIL, TELEFONE) VALUES ('Rafael Dorta', 'dorta@email.com', '(11)99999-9999');
INSERT INTO CLIENTE (NOME, EMAIL, TELEFONE) VALUES ('Wendel Henrique', 'henrique@email.com', '(11)99999-9999');


--Inserindo 1 endereco
INSERT INTO ENDERECO (BAIRRO, CEP, CIDADE, LOGRADOURO, NUMERO, PAIS, UF, CLIENTE_ID) VALUES ('Pimentas', '07179168', 'Guarulhos', 'Rua das Oliveiras', '100', 'Brasil', 'SP', 1);

-- Inserindo 1 conta
INSERT INTO CONTA (DATA_ABERTURA, SALDO, AGENCIA, SENHA, TIPO_CLIENTE, TIPO_CONTA, CLIENTE_ID, ENDERECO_ID) VALUES ('2022-04-09 12:32:39.439125', 0.00, 202, '123456', 'PESSOA_JURIDICA', 'CONTA_CORRENTE',1 ,1);
