INSERT INTO AGENCIA (ID, NOME, NUMERO_AGENCIA) VALUES (1,'Agencia Sul', 101);
INSERT INTO AGENCIA (ID, NOME, NUMERO_AGENCIA) VALUES (2,'Agencia Sudeste', 202);
INSERT INTO AGENCIA (ID, NOME, NUMERO_AGENCIA) VALUES (3,'Agencia Centro-Oeste', 303);
INSERT INTO AGENCIA (ID, NOME, NUMERO_AGENCIA) VALUES (5,'Agencia Nordeste', 404);
INSERT INTO AGENCIA (ID, NOME, NUMERO_AGENCIA) VALUES (4,'Agencia Norte', 505);
